export interface Photo {
  name: string;
  src: string;
  date: string;
}

export const photos: Photo[] = [
  { name: "天空之城", src: "/images/photos/airplane.jpg", date: "2020.10" },
  { name: "安吉露营", src: "/images/photos/anjiluying.jpg", date: "2022.12" },
  { name: "重庆", src: "/images/photos/chongqing.jpg", date: "2022.10" },
  { name: "重庆的桥", src: "/images/photos/chongqingqiao.jpg", date: "2022.10" },
  { name: "恋爱", src: "/images/photos/lianai.jpg", date: "2022.11" },
  { name: "普吉岛出海", src: "/images/photos/chuhai.jpg", date: "2018.12" },
  { name: "上海迪士尼", src: "/images/photos/dishini.jpg", date: "2022.10" },
  { name: "放风筝", src: "/images/photos/fangfengzhen.jpg", date: "2019.10" },
  { name: "可爱的狗狗", src: "/images/photos/gougou.jpg", date: "2019.10" },
  { name: "篝火", src: "/images/photos/gouhuo.jpg", date: "2022.12" },
  { name: "好天气", src: "/images/photos/haotianqi.jpg", date: "2020.12" },
  { name: "普吉岛的海", src: "/images/photos/kanhai.jpg", date: "2018.12" },
  { name: "快艇浪花", src: "/images/photos/kuaiting.jpg", date: "2018.12" },
  { name: "凌空的夜", src: "/images/photos/lingkongye.jpg", date: "2019.12" },
  { name: "凌空的傍晚", src: "/images/photos/linkong.jpg", date: "2019.10" },
  { name: "淀山湖露营", src: "/images/photos/luying.jpg", date: "2022.11" },
  { name: "淀山湖露营", src: "/images/photos/luyinggou.jpg", date: "2018.12" },
  { name: "我家可爱的猫", src: "/images/photos/mao.jpg", date: "2021.10" },
  { name: "我家可爱的猫", src: "/images/photos/mao2.jpg", date: "2021.10" },
  { name: "好吃的牛排", src: "/images/photos/meishi.jpg", date: "2022.11" },
  { name: "南京 · 明孝陵", src: "/images/photos/mingxiaoling.jpg", date: "2022.08" },
  { name: "莫干山 · 夏日漂流", src: "/images/photos/moganshanhaotianqi.jpg", date: "2022.07" },
  { name: "莫干山 · 猫", src: "/images/photos/moganshanmao.jpg", date: "2022.10" },
  { name: "南昌 · 摩天轮", src: "/images/photos/motianlun.jpg", date: "2017.09" },
  { name: "舟山 · 枸杞岛", src: "/images/photos/ongs.jpg", date: "2020.04" },
  { name: "普吉岛 · 日出", src: "/images/photos/pujidao.jpg", date: "2018.12" },
  { name: "朴树", src: "/images/photos/pushu.jpg", date: "2021.07" },
  { name: "千岛湖 · 烟雨江南", src: "/images/photos/qiandaohu.jpg", date: "2019.09" },
  { name: "启东 · 团建 · 玩水", src: "/images/photos/qidong.jpg", date: "2021.07" },
  { name: "山", src: "/images/photos/shan.jpg", date: "2019.10" },
  { name: "捕捉到的晚霞", src: "/images/photos/wanxia.jpg", date: "2022.07" },
  { name: "普吉岛 · 海", src: "/images/photos/water.jpg", date: "2018.12" },
  { name: "舟山 · 无人村", src: "/images/photos/wurencun.jpg", date: "2020.04" },
  { name: "梅雨上海", src: "/images/photos/xiayu.jpg", date: "2022.07" },
  { name: "宁波 · 象山", src: "/images/photos/xiebei.jpg", date: "2020.10" },
  { name: "西湖 · 樱花", src: "/images/photos/xihuyinghua.jpg", date: "2023.04" },
  { name: "上海的夜晚", src: "/images/photos/yeshanghai.jpg", date: "2021.08" },
  { name: "宜昌", src: "/images/photos/yichangshi.jpg", date: "2017.10" },
  { name: "解封后的外滩行", src: "/images/photos/yiqingwaitan.jpg", date: "2022.06" },
  { name: "民宿 · 泳池", src: "/images/photos/yongchi.jpg", date: "2022.07" },
  { name: "好看的云", src: "/images/photos/yun.jpg", date: "2022.07" },
];
